/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponseListString } from '../../models/user-response-list-string';

export interface GetNicknamesBatch$Params {
  ids: Array<number>;
}

export function getNicknamesBatch(http: HttpClient, rootUrl: string, params: GetNicknamesBatch$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseListString>> {
  const rb = new RequestBuilder(rootUrl, getNicknamesBatch.PATH, 'get');
  if (params) {
    rb.query('ids', params.ids, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseListString>;
    })
  );
}

getNicknamesBatch.PATH = '/api/users/nicknames';
