/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponseLong } from '../../models/comment-response-long';

export interface CountReplies$Params {
  parentCommentId: string;
}

export function countReplies(http: HttpClient, rootUrl: string, params: CountReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseLong>> {
  const rb = new RequestBuilder(rootUrl, countReplies.PATH, 'get');
  if (params) {
    rb.query('parentCommentId', params.parentCommentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponseLong>;
    })
  );
}

countReplies.PATH = '/api/comments/count/replies';
