/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponseVoid } from '../../models/user-response-void';

export interface BanUser$Params {
  id: number;
}

export function banUser(http: HttpClient, rootUrl: string, params: BanUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseVoid>> {
  const rb = new RequestBuilder(rootUrl, banUser.PATH, 'post');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseVoid>;
    })
  );
}

banUser.PATH = '/api/admins/ban/add';
