/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoResponsePhotoDto } from '../../models/photo-response-photo-dto';

export interface GetPhotoMetadata$Params {
  photoId: number;
}

export function getPhotoMetadata(http: HttpClient, rootUrl: string, params: GetPhotoMetadata$Params, context?: HttpContext): Observable<StrictHttpResponse<PhotoResponsePhotoDto>> {
  const rb = new RequestBuilder(rootUrl, getPhotoMetadata.PATH, 'get');
  if (params) {
    rb.query('photoId', params.photoId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PhotoResponsePhotoDto>;
    })
  );
}

getPhotoMetadata.PATH = '/api/photos/data/photo';
