/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhotoDto } from '../models/photo-dto';
export interface PhotoResponsePhotoDto {
  data?: PhotoDto;
  message?: string;
  status?: number;
  success?: boolean;
}
