/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PhotoResponseVoid {
  data?: {
};
  message?: string;
  status?: number;
  success?: boolean;
}
