---
apiVersion: v1
kind: ConfigMap
metadata:
  name: comment-service-config
  labels:
    app: comment-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_APPLICATION_NAME: "comment-service"
  SPRING_DATA_MONGODB_HOST: "comment-service-db"
  SPRING_DATA_MONGODB_PORT: "27018"
  SPRING_DATA_MONGODB_DATABASE: "comments_db"
  SPRING_DATA_REDIS_HOST: "redis" # ⬅️ aggiungi questa riga
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8180/realms/PhotoDom"
  LOKI_URL: "http://loki:3100/loki/api/v1/push"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
      - name: comment-service
        image: avalanchexd/photo-dom:comment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_APPLICATION_NAME
        - name: SPRING_DATA_MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_DATA_MONGODB_HOST
        - name: SPRING_DATA_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_DATA_MONGODB_PORT
        - name: SPRING_DATA_MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_DATA_MONGODB_DATABASE
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
        - name: LOKI_URL
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: LOKI_URL
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_DATA_REDIS_HOST
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: comment-service-config
              key: SPRING_DATA_REDIS_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        volumeMounts:
        - name: logs-dir
          mountPath: /workspace/logs
      volumes:
      - name: logs-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
