apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comment-mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service-db
spec:
  ports:
  - port: 27018
    targetPort: 27017
  selector:
    app: comment-service-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service-db
  template:
    metadata:
      labels:
        app: comment-service-db
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: comment-mongo-pvc
