# # ============================
# # 4. Kafka UI
# # ============================
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka-ui
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka-ui
#   template:
#     metadata:
#       labels:
#         app: kafka-ui
#     spec:
#       containers:
#       - name: kafka-ui
#         image: provectuslabs/kafka-ui:latest
#         ports:
#         - containerPort: 8090
#         env:
#         - name: KAFKA_CLUSTERS_0_NAME
#           value: local
#         - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
#           value: kafka:29092
#         - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
#           value: http://schema-registry:8091
#         - name: KAFKA_CLUSTERS_0_ZOOKEEPER
#           value: zookeeper:2181
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "50m"
#           limits:
#             memory: "128Mi"
#             cpu: "100m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-ui
# spec:
#   ports:
#   - port: 8090
#     targetPort: 8090
#   selector:
#     app: kafka-ui
# ============================
# Kafka UI ConfigMap
# ============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  labels:
    app: kafka-ui
  namespace: default
data:
  KAFKA_CLUSTERS_0_NAME: "local"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
  KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8091"
  KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
---
# ============================
# Kafka UI Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8090
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-ui-config
              key: KAFKA_CLUSTERS_0_NAME
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-ui-config
              key: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
          valueFrom:
            configMapKeyRef:
              name: kafka-ui-config
              key: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          valueFrom:
            configMapKeyRef:
              name: kafka-ui-config
              key: KAFKA_CLUSTERS_0_ZOOKEEPER
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# ============================
# Kafka UI Service
# ============================
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 8090
    targetPort: 8090
