apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak-custom:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8180
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        # - name: KC_HOSTNAME_STRICT
        #   value: "false"
        # - name: KC_HOSTNAME_URL
        #   value: http://keycloak:8180
        # - name: KC_HOSTNAME_ADMIN_URL
        #   value: http://keycloak:8180
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 8180
    targetPort: 8180
