# # ============================
# # 5. Loki
# # ============================
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: loki
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: loki
#   template:
#     metadata:
#       labels:
#         app: loki
#     spec:
#       containers:
#       - name: loki
#         image: grafana/loki:2.9.3
#         args:
#         - -config.file=/etc/loki/local-config.yaml
#         ports:
#         - containerPort: 3100
#         # volumeMounts:
#         # - name: loki-config
#         #   mountPath: /etc/loki/
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "50m"
#           limits:
#             memory: "128Mi"
#             cpu: "100m"
#       # volumes:
#       # - name: loki-config
#       #   configMap:
#       #     name: loki-config
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: loki
# spec:
#   selector:
#     app: loki
#   ports:
#   - port: 3100
#     targetPort: 3100
# ============================
# 5. Loki
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.3
        ports:
        - containerPort: 3100
        # Nessuna config custom, usa quella di default
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
