apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: photo-service-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: photo-service-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-service-mongo
  template:
    metadata:
      labels:
        app: photo-service-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: photo-mongo-pvc
