/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PhotoDto } from './models/photo-dto';
export type { PhotoResponsePhotoDto } from './models/photo-response-photo-dto';
export type { PhotoResponseString } from './models/photo-response-string';
export type { PhotoResponseVoid } from './models/photo-response-void';
