/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Comment } from './models/comment';
export type { CommentDto } from './models/comment-dto';
export type { CommentResponseLong } from './models/comment-response-long';
export type { CommentResponseString } from './models/comment-response-string';
export type { CommentResponseVoid } from './models/comment-response-void';
