/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileView {
  age?: number;
  birthday?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  nickname?: string;
  photoProfileId?: number;
  telephone?: string;
}
