/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  age?: number;
  birthday?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  nickname?: string;
  photoProfileId?: number;
  role?: 'USER' | 'ADMIN';
  status?: 'ACTIVE' | 'BANNED' | 'INACTIVE';
  telephone?: string;
  username?: string;
}
