/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProfileView } from '../models/profile-view';
export interface UserResponseProfileView {
  data?: ProfileView;
  message?: string;
  status?: number;
  success?: boolean;
}
