/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentResponseString {
  data?: string;
  message?: string;
  status?: number;
  success?: boolean;
}
