/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Comment {
  content?: string;
  createdDate?: string;
  id?: string;
  parentCommentId?: string;
  photoId?: string;
  replyIds?: Array<string>;
  userId?: string;
}
