server:
  port: 8761  # Porta su cui verrà eseguito il Discovery Service

eureka:
  client:
    register-with-eureka: false  # Il server non si registra con se stesso
    fetch-registry: false        # Il server non deve recuperare il registro, è il registro centrale

spring:
  application:
    name: discovery-service  # Nome del servizio per la registrazione
